#create secret with username and password, which has to be accessed in Spring Boot application
#for assigning values to secret keys use base64 format,
#for example run command in terminal `echo -n 'root' | base64` assign the result as value to key
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret
type: Opaque
data:
  mysql_root_password: Um9vdEAxMjM=
  mysql_username: cm9vdA==
  mysql_password: Um9vdEAxMjM=
