#Sbservice should start at 8081
server:
   port: 8081

spring:
  datasource:
    url: ${MYSQL_URL}  #assign value to url defined in deployment with key MYSQL_URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}     #assign value to username defined in deployment with key MYSQL_USERNAME
    password: ${MYSQL_PASSWORD} #assign value to password defined in deployment with key MYSQL_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


##Sbservice should start at 8081
#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo_db  #assign value to url defined in deployment with key MYSQL_URL
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root     #assign value to username defined in deployment with key MYSQL_USERNAME
#    password: Root@123 #assign value to password defined in deployment with key MYSQL_PASSWORD
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

